# Generated by Django 5.1.1 on 2024-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='dni',
            field=models.CharField(max_length=14),
        ),
    ]
