# Generated by Django 5.1.1 on 2024-09-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='rol',
            field=models.CharField(choices=[('inversor', 'Inversor'), ('operator', 'Operator')], default='', max_length=8),
        ),
    ]
