# Generated by Django 5.1.1 on 2024-09-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_expiringtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiringToken',
        ),
    ]
