# Generated by Django 5.1.1 on 2024-09-19 19:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.01, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01, message='El monto debe ser mayor que cero.')])),
                ('topic', models.CharField(default='General', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('anual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
