# Generated by Django 5.1.1 on 2024-09-22 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0006_alter_operation_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=20,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="El monto debe ser mayor que cero."
                    )
                ],
            ),
        ),
    ]
