# Generated by Django 5.1.1 on 2024-09-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operation", "0004_alter_operation_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operation.operation",
                    ),
                ),
            ],
        ),
    ]
