#!/usr/bin/env python3
# z-cron-old-operations/my_python

# import datetime
# now = datetime.datetime.now()
# print((now.strftime('%Y-%m-%d %H:%M:%S')))
# print("Hello World")


import os

import psycopg2
from psycopg2 import sql

# Obtener variables de entorno
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "mi_basededatos")
DB_USER = os.getenv("DB_USER", "usuario")
DB_PASSWORD = os.getenv("DB_PASSWORD", "contrasenia")


def get_db_connection():
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASSWORD,
        )
        return conn
    except Exception as e:
        print(f"Error de conexión a la base de datos: {e}")
        return None


def update_status():
    conn = get_db_connection()
    if conn is None:
        return

    try:
        with conn.cursor() as cur:
            update_query = sql.SQL(
                """
                UPDATE public.operation_operation
                SET status = false
                WHERE end_date < CURRENT_DATE;
                """
            )
            cur.execute(update_query)
            conn.commit()
            print(
                "Status actualizado para todos los registros"
                "cuya fecha de fin es menor a la fecha actual"
            )
    except Exception as e:
        conn.rollback()
        print(f"Error al actualizar el estado: {e}")
    finally:
        conn.close()


if __name__ == "__main__":
    update_status()
